// Genel (YDS dışı) başlangıç kelimeleri. [İngilizce, Türkçe, Eş anlamlı, Örnek cümle, tür, ek anlamlar, örnek cümle çevirisi]
window.LEGACY_ROWS = [
["abandon","terk etmek","desert, leave","He had to abandon his car in the snow.",null,null,"Arabasını karda bırakmak zorunda kaldı."],
["ability","yetenek, yeti","skill, talent","She has the ability to learn languages quickly.",null,null,"Dilleri hızlı öğrenme yeteneği var."],
["accept","kabul etmek","agree to, receive","I accept your invitation with pleasure.",null,null,"Davetini memnuniyetle kabul ediyorum."],
["achieve","başarmak","accomplish, attain","You can achieve anything if you work hard.",null,null,"Çok çalışırsan her şeyi başarabilirsin."],
["advice","tavsiye","guidance, suggestion","Thank you for your advice about the job.",null,null,"İş konusundaki tavsiyen için teşekkürler."],
["afford","gücü yetmek","manage to pay","We can't afford a new car right now.",null,null,"Şu anda yeni bir araba alamayız."],
["agree","aynı fikirde olmak","consent, concur","I agree with you completely.",null,null,"Seninle tamamen aynı fikirdeyim."],
["allow","izin vermek","permit, let","They don't allow phones in the exam room.",null,null,"Sınav salonuna telefon sokmaya izin vermiyorlar."],
["amazing","şaşırtıcı, harika","astonishing, wonderful","The view from the top was amazing.",null,null,"Tepeden manzara harikaydı."],
["ancient","antik, çok eski","old, archaic","We visited an ancient temple in Greece.",null,null,"Yunanistan'da antik bir tapınağı gezdik."],
["annoy","sinirlendirmek","irritate, bother","The noise really annoys me.",null,null,"Gürültü beni gerçekten sinirlendiriyor."],
["appear","görünmek, ortaya çıkmak","emerge, show up","A rainbow appeared after the rain.",null,null,"Yağmurdan sonra gökkuşağı belirdi."],
["argue","tartışmak","quarrel, debate","They always argue about money.",null,null,"Her zaman para konusunda tartışıyorlar."],
["arrange","düzenlemek, ayarlamak","organize, set up","I'll arrange a meeting for Monday.",null,null,"Pazartesi için bir toplantı ayarlayacağım."],
["attempt","girişim, denemek","try, effort","He made an attempt to fix the sink.",null,null,"Lavabonun tamiri için bir girişimde bulundu."],
["avoid","kaçınmak","evade, steer clear of","Try to avoid sugary drinks.",null,null,"Şekerli içeceklerden kaçınmaya çalış."],
["aware","farkında","conscious, mindful","Are you aware of the problem?",null,null,"Sorunun farkında mısın?"],
["basic","temel","fundamental, essential","You need a basic knowledge of English.",null,null,"Temel düzeyde İngilizce bilgisine ihtiyacın var."],
["benefit","fayda, yarar","advantage, gain","Exercise has many health benefits.",null,null,"Egzersizin sağlığa birçok faydası var."],
["borrow","ödünç almak","take on loan","Can I borrow your pen?",null,null,"Kalemini ödünç alabilir miyim?"],
["brave","cesur","courageous, fearless","The brave firefighter saved the child.",null,null,"Cesur itfaiyeci çocuğu kurtardı."],
["breathe","nefes almak","inhale and exhale","Breathe deeply and relax.",null,null,"Derin nefes al ve gevşe."],
["budget","bütçe","spending plan, funds","We have a tight budget this month.",null,null,"Bu ay bütçemiz kısıtlı."],
["calm","sakin","peaceful, relaxed","Stay calm and listen to me.",null,null,"Sakin ol ve beni dinle."],
["cancel","iptal etmek","call off, scrap","They had to cancel the flight.",null,null,"Uçuşu iptal etmek zorunda kaldılar."],
["careful","dikkatli","cautious, attentive","Be careful with that hot pan.",null,null,"O sıcak tavaya dikkat et."],
["challenge","zorluk, meydan okuma","test, difficulty","Learning a new language is a challenge.",null,null,"Yeni bir dil öğrenmek bir meydan okumadır."],
["choose","seçmek","select, pick","You can choose any color you like.",null,null,"İstediğin rengi seçebilirsin."],
["clear","net, açık","obvious, transparent","The instructions were very clear.",null,null,"Talimatlar çok netti."],
["common","yaygın, ortak","usual, widespread","Smith is a common surname.",null,null,"Smith yaygın bir soyadıdır."],
["compare","karşılaştırmak","contrast, weigh","Don't compare yourself to others.",null,null,"Kendini başkalarıyla kıyaslama."],
["complain","şikayet etmek","grumble, protest","Customers complain about the slow service.",null,null,"Müşteriler yavaş hizmetten şikayet ediyor."],
["confident","kendinden emin","self-assured, sure","She felt confident before the interview.",null,null,"Mülakattan önce kendinden emin hissetti."],
["consider","düşünmek, göz önünde bulundurmak","think about, contemplate","Consider all the options before you decide.",null,null,"Karar vermeden önce tüm seçenekleri düşün."],
["convince","ikna etmek","persuade, assure","I couldn't convince him to stay.",null,null,"Onu kalması için ikna edemedim."],
["create","yaratmak, oluşturmak","make, produce","Artists create beautiful things.",null,null,"Sanatçılar güzel şeyler yaratır."],
["curious","meraklı","inquisitive, interested","Children are naturally curious.",null,null,"Çocuklar doğal olarak meraklıdır."],
["damage","hasar, zarar vermek","harm, injury","The storm caused serious damage.",null,null,"Fırtına ciddi hasara yol açtı."],
["decide","karar vermek","determine, resolve","We decided to take the train.",null,null,"Trene binmeye karar verdik."],
["delay","gecikme, ertelemek","postpone, hold up","The delay lasted two hours.",null,null,"Gecikme iki saat sürdü."],
["deliver","teslim etmek","hand over, bring","They deliver pizza in thirty minutes.",null,null,"Pizzayı otuz dakikada teslim ediyorlar."],
["depend","bağlı olmak","rely, hinge","It depends on the weather.",null,null,"Hava durumuna bağlı."],
["describe","tanımlamak, anlatmak","portray, explain","Can you describe the man you saw?",null,null,"Gördüğün adamı tarif edebilir misin?"],
["develop","geliştirmek, gelişmek","grow, expand","The company develops mobile apps.",null,null,"Şirket mobil uygulamalar geliştiriyor."],
["difficult","zor","hard, tough","This exam was really difficult.",null,null,"Bu sınav gerçekten zordu."],
["discover","keşfetmek","find out, uncover","Scientists discovered a new planet.",null,null,"Bilim insanları yeni bir gezegen keşfetti."],
["doubt","şüphe, şüphe duymak","uncertainty, suspect","I doubt that he will come.",null,null,"Onun geleceğinden şüpheliyim."],
["during","...boyunca","throughout, while","I fell asleep during the movie.",null,null,"Film sırasında uyuyakaldım."],
["earn","kazanmak (para, hak)","make, deserve","She earns a good salary.",null,null,"İyi bir maaş kazanıyor."],
["effort","çaba","attempt, exertion","It takes a lot of effort to learn.",null,null,"Öğrenmek çok çaba gerektirir."],
["encourage","cesaretlendirmek","motivate, support","My teacher encouraged me to apply.",null,null,"Öğretmenim başvurmam için beni cesaretlendirdi."],
["enough","yeterli","sufficient, adequate","We have enough food for everyone.",null,null,"Herkese yetecek kadar yemeğimiz var."],
["environment","çevre","surroundings, nature","We must protect the environment.",null,null,"Çevreyi korumalıyız."],
["essential","gerekli, şart","vital, necessary","Water is essential for life.",null,null,"Su, yaşam için şarttır."],
["exact","tam, kesin","precise, accurate","What is the exact time?",null,null,"Tam saat kaç?"],
["expect","beklemek, ummak","anticipate, await","I didn't expect to see you here.",null,null,"Seni burada görmeyi beklemiyordum."],
["experience","deneyim, tecrübe","practice, involvement","She has five years of experience.",null,null,"Beş yıllık tecrübesi var."],
["explain","açıklamak","clarify, describe","Please explain how this works.",null,null,"Lütfen bunun nasıl çalıştığını açıkla."],
["familiar","tanıdık, aşina","well-known, recognizable","Your face looks familiar to me.",null,null,"Yüzün bana tanıdık geliyor."],
["fear","korku","fright, dread","Fear of failure stops many people.",null,null,"Başarısızlık korkusu birçok insanı durduruyor."],
["forgive","affetmek","pardon, excuse","Please forgive me for being late.",null,null,"Geç kaldığım için lütfen beni affet."],
["generous","cömert","giving, kind","He is generous with his time.",null,null,"Zamanı konusunda cömerttir."],
["gradually","yavaş yavaş","slowly, step by step","Her English gradually improved.",null,null,"İngilizcesi yavaş yavaş gelişti."],
["guess","tahmin etmek","estimate, suppose","Can you guess my age?",null,null,"Yaşımı tahmin edebilir misin?"],
["handle","ele almak, başa çıkmak","manage, deal with","She handled the situation well.",null,null,"Durumu iyi idare etti."],
["honest","dürüst","truthful, sincere","Please be honest with me.",null,null,"Lütfen bana karşı dürüst ol."],
["improve","geliştirmek, iyileşmek","enhance, get better","I want to improve my speaking.",null,null,"Konuşmamı geliştirmek istiyorum."],
["increase","artmak, artış","grow, rise","Prices increase every year.",null,null,"Fiyatlar her yıl artıyor."],
["influence","etki, etkilemek","effect, impact","Parents influence their children's habits.",null,null,"Ebeveynler çocuklarının alışkanlıklarını etkiler."],
["ignore","görmezden gelmek","disregard, overlook","Don't ignore the warning signs.",null,null,"Uyarı işaretlerini görmezden gelme."],
["knowledge","bilgi","understanding, learning","Reading expands your knowledge.",null,null,"Okumak bilgini genişletir."],
["lazy","tembel","idle, lethargic","I felt lazy on Sunday morning.",null,null,"Pazar sabahı tembel hissettim."],
["limit","sınır, sınırlamak","boundary, restrict","There is a limit to what I can do.",null,null,"Yapabileceklerimin bir sınırı var."],
["manage","başarmak, yönetmek","run, cope","She manages a small team.",null,null,"Küçük bir ekibi yönetiyor."],
["mention","bahsetmek","refer to, state","He didn't mention the meeting.",null,null,"Toplantıdan bahsetmedi."],
["necessary","gerekli","needed, required","Is it necessary to book in advance?",null,null,"Önceden rezervasyon yaptırmak gerekli mi?"],
["notice","fark etmek","spot, observe","Did you notice her new haircut?",null,null,"Yeni saç kesimini fark ettin mi?"],
["obvious","apaçık, belli","clear, evident","The answer is obvious.",null,null,"Cevap apaçık ortada."],
["opportunity","fırsat","chance, opening","This job is a great opportunity.",null,null,"Bu iş harika bir fırsat."],
["prefer","tercih etmek","favor, like better","I prefer tea to coffee.",null,null,"Çayı kahveye tercih ederim."],
["prevent","önlemek","stop, avoid","Vaccines prevent many diseases.",null,null,"Aşılar birçok hastalığı önler."],
["promise","söz, söz vermek","pledge, vow","I promise I will call you.",null,null,"Söz veriyorum seni arayacağım."],
["realize","fark etmek, anlamak","understand, grasp","I realized I had left my keys at home.",null,null,"Anahtarlarımı evde unuttuğumu fark ettim."],
["recent","yakın zamanlı, son","latest, new","Have you seen any recent movies?",null,null,"Yakın zamanda film izledin mi?"],
["reduce","azaltmak","decrease, cut","We need to reduce waste.",null,null,"Atığı azaltmamız gerekiyor."],
["refuse","reddetmek","decline, turn down","He refused to answer the question.",null,null,"Soruyu yanıtlamayı reddetti."],
["regret","pişmanlık, pişman olmak","remorse, rue","I regret not studying harder.",null,null,"Daha çok çalışmadığım için pişmanım."],
["rely","güvenmek, dayanmak","depend, count on","You can rely on me.",null,null,"Bana güvenebilirsin."],
["remind","hatırlatmak","prompt, jog memory","Remind me to buy milk.",null,null,"Bana süt almamı hatırlat."],
["rare","nadir","uncommon, scarce","This coin is very rare.",null,null,"Bu madeni para çok nadirdir."],
["succeed","başarılı olmak","triumph, prosper","If you keep trying, you will succeed.",null,null,"Denemeye devam edersen başaracaksın."],
["suggest","önermek","propose, recommend","I suggest we leave early.",null,null,"Erken çıkmamızı öneriyorum."],
["surprise","sürpriz, şaşırtmak","shock, astonish","The party was a complete surprise.",null,null,"Parti tam bir sürprizdi."],
["tend","eğilimli olmak","be inclined, usually","I tend to wake up early.",null,null,"Erken uyanma eğilimindeyim."],
["tight","sıkı, dar","snug, firm","These shoes are too tight.",null,null,"Bu ayakkabılar çok dar."],
["trust","güven, güvenmek","faith, rely on","Trust takes years to build.",null,null,"Güven oluşturmak yıllar alır."],
["useful","faydalı","helpful, handy","This app is really useful.",null,null,"Bu uygulama gerçekten faydalı."],
["wonder","merak etmek, harika","ponder, marvel","I wonder what time it is.",null,null,"Saat kaç acaba, merak ediyorum."],
["worry","endişelenmek","fret, be anxious","Don't worry, everything will be fine.",null,null,"Merak etme, her şey yoluna girecek."]
];
