// [İngilizce, Türkçe, Eş anlamlı, Örnek cümle]
window.WORDS = [
["abandon","terk etmek","desert, leave","He had to abandon his car in the snow."],
["ability","yetenek, yeti","skill, talent","She has the ability to learn languages quickly."],
["accept","kabul etmek","agree to, receive","I accept your invitation with pleasure."],
["achieve","başarmak","accomplish, attain","You can achieve anything if you work hard."],
["advice","tavsiye","guidance, suggestion","Thank you for your advice about the job."],
["afford","gücü yetmek","manage to pay","We can't afford a new car right now."],
["agree","aynı fikirde olmak","consent, concur","I agree with you completely."],
["allow","izin vermek","permit, let","They don't allow phones in the exam room."],
["amazing","şaşırtıcı, harika","astonishing, wonderful","The view from the top was amazing."],
["ancient","antik, çok eski","old, archaic","We visited an ancient temple in Greece."],
["annoy","sinirlendirmek","irritate, bother","The noise really annoys me."],
["appear","görünmek, ortaya çıkmak","emerge, show up","A rainbow appeared after the rain."],
["argue","tartışmak","quarrel, debate","They always argue about money."],
["arrange","düzenlemek, ayarlamak","organize, set up","I'll arrange a meeting for Monday."],
["attempt","girişim, denemek","try, effort","He made an attempt to fix the sink."],
["avoid","kaçınmak","evade, steer clear of","Try to avoid sugary drinks."],
["aware","farkında","conscious, mindful","Are you aware of the problem?"],
["basic","temel","fundamental, essential","You need a basic knowledge of English."],
["benefit","fayda, yarar","advantage, gain","Exercise has many health benefits."],
["borrow","ödünç almak","take on loan","Can I borrow your pen?"],
["brave","cesur","courageous, fearless","The brave firefighter saved the child."],
["breathe","nefes almak","inhale and exhale","Breathe deeply and relax."],
["budget","bütçe","spending plan, funds","We have a tight budget this month."],
["calm","sakin","peaceful, relaxed","Stay calm and listen to me."],
["cancel","iptal etmek","call off, scrap","They had to cancel the flight."],
["careful","dikkatli","cautious, attentive","Be careful with that hot pan."],
["challenge","zorluk, meydan okuma","test, difficulty","Learning a new language is a challenge."],
["choose","seçmek","select, pick","You can choose any color you like."],
["clear","net, açık","obvious, transparent","The instructions were very clear."],
["common","yaygın, ortak","usual, widespread","Smith is a common surname."],
["compare","karşılaştırmak","contrast, weigh","Don't compare yourself to others."],
["complain","şikayet etmek","grumble, protest","Customers complain about the slow service."],
["confident","kendinden emin","self-assured, sure","She felt confident before the interview."],
["consider","düşünmek, göz önünde bulundurmak","think about, contemplate","Consider all the options before you decide."],
["convince","ikna etmek","persuade, assure","I couldn't convince him to stay."],
["create","yaratmak, oluşturmak","make, produce","Artists create beautiful things."],
["curious","meraklı","inquisitive, interested","Children are naturally curious."],
["damage","hasar, zarar vermek","harm, injury","The storm caused serious damage."],
["decide","karar vermek","determine, resolve","We decided to take the train."],
["delay","gecikme, ertelemek","postpone, hold up","The delay lasted two hours."],
["deliver","teslim etmek","hand over, bring","They deliver pizza in thirty minutes."],
["depend","bağlı olmak","rely, hinge","It depends on the weather."],
["describe","tanımlamak, anlatmak","portray, explain","Can you describe the man you saw?"],
["develop","geliştirmek, gelişmek","grow, expand","The company develops mobile apps."],
["difficult","zor","hard, tough","This exam was really difficult."],
["discover","keşfetmek","find out, uncover","Scientists discovered a new planet."],
["doubt","şüphe, şüphe duymak","uncertainty, suspect","I doubt that he will come."],
["during","...boyunca","throughout, while","I fell asleep during the movie."],
["earn","kazanmak (para, hak)","make, deserve","She earns a good salary."],
["effort","çaba","attempt, exertion","It takes a lot of effort to learn."],
["encourage","cesaretlendirmek","motivate, support","My teacher encouraged me to apply."],
["enough","yeterli","sufficient, adequate","We have enough food for everyone."],
["environment","çevre","surroundings, nature","We must protect the environment."],
["essential","gerekli, şart","vital, necessary","Water is essential for life."],
["exact","tam, kesin","precise, accurate","What is the exact time?"],
["expect","beklemek, ummak","anticipate, await","I didn't expect to see you here."],
["experience","deneyim, tecrübe","practice, involvement","She has five years of experience."],
["explain","açıklamak","clarify, describe","Please explain how this works."],
["familiar","tanıdık, aşina","well-known, recognizable","Your face looks familiar to me."],
["fear","korku","fright, dread","Fear of failure stops many people."],
["forgive","affetmek","pardon, excuse","Please forgive me for being late."],
["generous","cömert","giving, kind","He is generous with his time."],
["gradually","yavaş yavaş","slowly, step by step","Her English gradually improved."],
["guess","tahmin etmek","estimate, suppose","Can you guess my age?"],
["handle","ele almak, başa çıkmak","manage, deal with","She handled the situation well."],
["honest","dürüst","truthful, sincere","Please be honest with me."],
["improve","geliştirmek, iyileşmek","enhance, get better","I want to improve my speaking."],
["increase","artmak, artış","grow, rise","Prices increase every year."],
["influence","etki, etkilemek","effect, impact","Parents influence their children's habits."],
["ignore","görmezden gelmek","disregard, overlook","Don't ignore the warning signs."],
["knowledge","bilgi","understanding, learning","Reading expands your knowledge."],
["lazy","tembel","idle, lethargic","I felt lazy on Sunday morning."],
["limit","sınır, sınırlamak","boundary, restrict","There is a limit to what I can do."],
["manage","başarmak, yönetmek","run, cope","She manages a small team."],
["mention","bahsetmek","refer to, state","He didn't mention the meeting."],
["necessary","gerekli","needed, required","Is it necessary to book in advance?"],
["notice","fark etmek","spot, observe","Did you notice her new haircut?"],
["obvious","apaçık, belli","clear, evident","The answer is obvious."],
["opportunity","fırsat","chance, opening","This job is a great opportunity."],
["prefer","tercih etmek","favor, like better","I prefer tea to coffee."],
["prevent","önlemek","stop, avoid","Vaccines prevent many diseases."],
["promise","söz, söz vermek","pledge, vow","I promise I will call you."],
["realize","fark etmek, anlamak","understand, grasp","I realized I had left my keys at home."],
["recent","yakın zamanlı, son","latest, new","Have you seen any recent movies?"],
["reduce","azaltmak","decrease, cut","We need to reduce waste."],
["refuse","reddetmek","decline, turn down","He refused to answer the question."],
["regret","pişmanlık, pişman olmak","remorse, rue","I regret not studying harder."],
["rely","güvenmek, dayanmak","depend, count on","You can rely on me."],
["remind","hatırlatmak","prompt, jog memory","Remind me to buy milk."],
["rare","nadir","uncommon, scarce","This coin is very rare."],
["succeed","başarılı olmak","triumph, prosper","If you keep trying, you will succeed."],
["suggest","önermek","propose, recommend","I suggest we leave early."],
["surprise","sürpriz, şaşırtmak","shock, astonish","The party was a complete surprise."],
["tend","eğilimli olmak","be inclined, usually","I tend to wake up early."],
["tight","sıkı, dar","snug, firm","These shoes are too tight."],
["trust","güven, güvenmek","faith, rely on","Trust takes years to build."],
["useful","faydalı","helpful, handy","This app is really useful."],
["wonder","merak etmek, harika","ponder, marvel","I wonder what time it is."],
["worry","endişelenmek","fret, be anxious","Don't worry, everything will be fine."]
].map((w,i)=>({id:i,en:w[0],tr:w[1],syn:w[2],ex:w[3]}));
