// OTOMATİK ÜRETİLDİ: node tools/build-words.js  (kaynak: data/conj-*.json)
window.CONJ_ROWS = [
["however","ancak, bununla birlikte","nevertheless, yet","The plan looks good; however, it is too expensive.","conj",null,"Plan iyi görünüyor; ancak çok pahalı.","zıtlık"],
["whereas","oysa, -dığı halde","while","Some students prefer lectures, whereas others learn better in groups.","conj",null,"Bazı öğrenciler derslere, oysa diğerleri grup çalışmasıyla daha iyi öğrenir.","zıtlık"],
["on the other hand","öte yandan","conversely","Cities offer jobs; on the other hand, they are often overcrowded.","conj",null,"Şehirler iş sunar; öte yandan çoğu zaman aşırı kalabalıktır.","zıtlık"],
["in contrast","buna karşılık, aksine","by contrast","Northern regions are cold; in contrast, the south is warm all year.","conj",null,"Kuzey bölgeleri soğuktur; buna karşılık güney yıl boyunca sıcaktır.","zıtlık"],
["on the contrary","tam tersine","quite the opposite","The treatment did not help; on the contrary, it made the symptoms worse.","conj",null,"Tedavi işe yaramadı; tam tersine belirtileri kötüleştirdi.","zıtlık"],
["instead","bunun yerine","alternatively","He did not go to the party; instead, he stayed home and studied.","conj",null,"Partiye gitmedi; bunun yerine evde kalıp çalıştı.","zıtlık"],
["rather than","-mektense, -ması yerine","instead of","Many people choose to cycle rather than drive to work.","conj",null,"Birçok kişi işe araba kullanmak yerine bisikletle gitmeyi seçiyor.","zıtlık"],
["but","ama, fakat","yet","The experiment was simple but the results were remarkable.","conj",null,"Deney basitti ama sonuçlar dikkat çekiciydi.","zıtlık"],
["yet","yine de, ancak","but, nevertheless","The theory is widely accepted, yet no one has fully proven it.","conj",null,"Teori yaygın biçimde kabul görüyor, yine de kimse onu tam olarak kanıtlamadı.","zıtlık"],
["although","-e rağmen, -dığı halde","though, even though","Although the test was difficult, most students passed it.","conj",null,"Sınav zor olmasına rağmen öğrencilerin çoğu geçti.","kabul/ödün"],
["even though","her ne kadar, -e rağmen","although","Even though he was exhausted, he kept working.","conj",null,"Çok yorgun olmasına rağmen çalışmaya devam etti.","kabul/ödün"],
["despite","-e rağmen","in spite of","Despite the heavy rain, the match was not cancelled.","conj",null,"Şiddetli yağmura rağmen maç iptal edilmedi.","kabul/ödün"],
["in spite of","-e rağmen","despite","In spite of his illness, he attended the conference.","conj",null,"Hastalığına rağmen konferansa katıldı.","kabul/ödün"],
["nevertheless","yine de, buna rağmen","nonetheless, however","The risks are high; nevertheless, many investors are willing to take them.","conj",null,"Riskler yüksek; yine de birçok yatırımcı bu riskleri almaya istekli.","kabul/ödün"],
["nonetheless","yine de, bununla birlikte","nevertheless","The results were disappointing; nonetheless, the team will continue its research.","conj",null,"Sonuçlar hayal kırıcıydı; yine de ekip araştırmasını sürdürecek.","kabul/ödün"],
["while","iken; oysa; -dığı halde","whereas, although","While some people enjoy city life, others long for the countryside.","conj",null,"Bazı insanlar şehir hayatından keyif alırken diğerleri kırsalı özler.","zıtlık"],
["because","çünkü, -dığı için","since, as","The match was postponed because the pitch was flooded.","conj",null,"Saha su bastığı için maç ertelendi.","sebep"],
["since","-dığı için; -den beri","because, as","Since resources are limited, they must be used wisely.","conj",null,"Kaynaklar sınırlı olduğu için akıllıca kullanılmalıdır.","sebep"],
["owing to","-den dolayı, yüzünden","due to, because of","Owing to a technical fault, the flight was delayed by three hours.","conj",null,"Teknik bir arıza nedeniyle uçuş üç saat gecikti.","sebep"],
["due to","-den dolayı, -e bağlı olarak","owing to, because of","The shortage was due to poor harvests in several regions.","conj",null,"Kıtlık, birkaç bölgedeki kötü hasattan kaynaklanıyordu.","sebep"],
["thanks to","sayesinde","owing to","Thanks to modern technology, communication has become much faster.","conj",null,"Modern teknoloji sayesinde iletişim çok daha hızlı hale geldi.","sebep"],
["given that","-dığı göz önüne alındığında","considering that, since","Given that demand is rising, prices are unlikely to fall.","conj",null,"Talebin arttığı düşünüldüğünde fiyatların düşmesi olası değil.","sebep"],
["therefore","bu nedenle, dolayısıyla","thus, hence, consequently","The sample was small; therefore, the findings cannot be generalised.","conj",null,"Örneklem küçüktü; bu nedenle bulgular genellenemez.","sonuç"],
["thus","böylece, bu şekilde","therefore, hence","Costs fell sharply, thus making the product more affordable.","conj",null,"Maliyetler keskin biçimde düştü ve böylece ürün daha uygun fiyatlı hale geldi.","sonuç"],
["hence","bu yüzden, dolayısıyla","therefore, thus","The soil is poor; hence, crop yields remain low.","conj",null,"Toprak fakir; bu yüzden ürün verimi düşük kalıyor.","sonuç"],
["consequently","sonuç olarak, bu nedenle","as a result, therefore","Funding was cut; consequently, several projects were abandoned.","conj",null,"Fon kesildi; sonuç olarak birkaç proje terk edildi.","sonuç"],
["as a result","sonuç olarak","consequently","It rained heavily all week; as a result, the river overflowed.","conj",null,"Bütün hafta şiddetli yağmur yağdı; sonuç olarak nehir taştı.","sonuç"],
["accordingly","buna göre, bu doğrultuda","correspondingly","Conditions have changed, and the rules must be updated accordingly.","conj",null,"Koşullar değişti ve kurallar buna göre güncellenmeli.","sonuç"],
["moreover","dahası, üstelik","furthermore, besides","The car is cheap; moreover, it is extremely reliable.","conj",null,"Araba ucuz; üstelik son derece güvenilir.","ekleme"],
["furthermore","dahası, ayrıca","moreover, in addition","The method is fast; furthermore, it is inexpensive.","conj",null,"Yöntem hızlı; dahası ucuz.","ekleme"],
["in addition","ek olarak, ayrıca","besides, furthermore","In addition to the salary, employees receive health insurance.","conj",null,"Maaşa ek olarak çalışanlar sağlık sigortası alır.","ekleme"],
["besides","ayrıca, bunun yanı sıra","moreover, apart from","I don't want to go out; besides, it is raining.","conj",null,"Dışarı çıkmak istemiyorum; ayrıca yağmur yağıyor.","ekleme"],
["as well as","-in yanı sıra, hem de","in addition to","She speaks French as well as German and Spanish.","conj",null,"Almanca ve İspanyolcanın yanı sıra Fransızca da konuşuyor.","ekleme"],
["likewise","aynı şekilde, benzer biçimde","similarly","Wages have risen; likewise, the cost of living has increased.","conj",null,"Ücretler yükseldi; aynı şekilde yaşam maliyeti de arttı.","ekleme"],
["similarly","benzer şekilde","likewise","Children learn by imitation; similarly, adults pick up habits from colleagues.","conj",null,"Çocuklar taklit ederek öğrenir; benzer şekilde yetişkinler de iş arkadaşlarından alışkanlık edinir.","ekleme"],
["unless","-medikçe, -mezse","if not, except if","The plants will die unless they are watered regularly.","conj",null,"Bitkiler düzenli sulanmazsa ölecek.","koşul"],
["provided that","-mak koşuluyla","as long as, on condition that","The loan will be approved provided that all documents are submitted.","conj",null,"Tüm belgeler teslim edilmesi koşuluyla kredi onaylanacak.","koşul"],
["as long as","-dığı sürece, -mak şartıyla","provided that","You can borrow the book as long as you return it next week.","conj",null,"Kitabı gelecek hafta iade etmen şartıyla ödünç alabilirsin.","koşul"],
["in case","-e karşı, -ması ihtimaline karşı","if, for fear that","Take an umbrella in case it rains.","conj",null,"Yağmur yağarsa diye şemsiye al.","koşul"],
["otherwise","aksi halde, yoksa","if not, or else","Submit the report today; otherwise, you will lose the grant.","conj",null,"Raporu bugün teslim et; aksi halde hibeyi kaybedeceksin.","koşul"],
["whether","-ip -mediği, -mi","if","It is not yet clear whether the new policy will work.","conj",null,"Yeni politikanın işe yarayıp yaramayacağı henüz belli değil.","koşul"],
["meanwhile","bu arada, o sırada","in the meantime","The government debated the law; meanwhile, protests spread across the country.","conj",null,"Hükümet yasayı tartışırken ülke genelinde protestolar yayıldı.","zaman"],
["as soon as","-ir -mez, -er etmez","once, the moment","We will contact you as soon as the results are ready.","conj",null,"Sonuçlar hazır olur olmaz sizinle iletişime geçeceğiz.","zaman"],
["until","-e kadar","till, up to the time that","The patient must rest until the wound has healed.","conj",null,"Hasta, yara iyileşene kadar dinlenmelidir.","zaman"],
["once","-dığında, bir kez -ince","as soon as, after","Once the data are collected, they will be analysed.","conj",null,"Veriler toplandıktan sonra analiz edilecek.","zaman"],
["subsequently","sonradan, ardından","afterwards, later","The company was founded in 1990 and subsequently expanded abroad.","conj",null,"Şirket 1990'da kuruldu ve ardından yurt dışına açıldı.","zaman"],
["previously","daha önce","before, formerly","The disease, previously thought to be rare, is now increasingly common.","conj",null,"Daha önce nadir sanılan hastalık artık giderek yaygınlaşıyor.","zaman"],
["in order to","-mek için","so as to","Students must study hard in order to pass the exam.","conj",null,"Öğrenciler sınavı geçmek için çok çalışmalıdır.","amaç"],
["so that","-sın diye, -mesi için","in order that","Speak slowly so that everyone can understand you.","conj",null,"Herkes seni anlasın diye yavaş konuş.","amaç"],
["so as to","-mek amacıyla","in order to","They left early so as to avoid the traffic.","conj",null,"Trafikten kaçınmak amacıyla erken ayrıldılar.","amaç"],
["for instance","örneğin","for example","Many countries, for instance Japan, have ageing populations.","conj",null,"Japonya gibi birçok ülkenin nüfusu yaşlanıyor.","örnekleme"],
["namely","yani, başka bir deyişle (örnek verirken)","that is to say","Two factors were decisive, namely cost and quality.","conj",null,"İki etken belirleyiciydi, yani maliyet ve kalite.","örnekleme"],
["in particular","özellikle","especially, notably","Young people, in particular, are affected by unemployment.","conj",null,"İşsizlikten özellikle gençler etkileniyor.","örnekleme"],
["in other words","başka bir deyişle","that is to say","The device is energy-efficient; in other words, it saves money.","conj",null,"Cihaz enerji verimli; başka bir deyişle para tasarrufu sağlıyor.","vurgu"],
["indeed","gerçekten, hatta","in fact, actually","The results were good; indeed, they exceeded all expectations.","conj",null,"Sonuçlar iyiydi; hatta tüm beklentileri aştı.","vurgu"],
["in fact","aslında, gerçekte","actually, indeed","Many believe the task is easy; in fact, it requires great skill.","conj",null,"Birçok kişi işin kolay olduğunu sanıyor; aslında büyük beceri gerektiriyor.","vurgu"]
];
